# Generated by Django 4.1.2 on 2023-04-28 11:34

from django.db import migrations


class Migration(migrations.Migration):
    def link_brands(apps, schema_editor):
        Product = apps.get_model("apis", "Product")
        Brands = apps.get_model("apis", "Brand")
        User = apps.get_model("apis", "User")
        user = User.objects.get(username="admin")
        for product in Product.objects.all():
            brand, created = Brands.objects.get_or_create(name=product.brand, added_by=user)
            product.brand_link = brand
            product.save()

    dependencies = [
        ("apis", "0006_brand_product_brand_link"),
    ]

    operations = [
        migrations.RunPython(link_brands),
    ]
