# Generated by Django 4.1.2 on 2023-04-28 11:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apis", "0007_transfer_brands"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="brand",
        ),
    ]
