# Generated by Django 4.1.2 on 2023-04-28 11:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apis", "0008_remove_product_brand"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="brand_link",
            new_name="brand",
        ),
    ]
