# Generated by Django 4.1.2 on 2023-04-28 11:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis", "0009_rename_brand_link_product_brand"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="slug",
            field=models.SlugField(
                blank=True,
                error_messages={"unique": "Brandwith exact name Already Exists"},
                max_length=200,
                null=True,
                unique=True,
            ),
        ),
    ]
