# Generated by Django 4.1.2 on 2023-05-08 10:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis", "0011_alter_brand_slug_banner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banner",
            name="redirect_url",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
