# Generated by Django 4.1.2 on 2022-11-03 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_alter_product_avg_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, error_messages={'unique': 'Product with exact name Already Exists'}, max_length=200, null=True, unique=True),
        ),
    ]
